server:
  port: 8088

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8094
  application:
    name: biller-service

  datasource:
    url: jdbc:postgresql://localhost:5432/billerdb
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    clean-disabled: true

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG

auth:
  jwt:
    audience: https://mockbank/api
